//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Profane.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ProfaneParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IProfaneListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProfaneParser.compilation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompilation_unit([NotNull] ProfaneParser.Compilation_unitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProfaneParser.compilation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompilation_unit([NotNull] ProfaneParser.Compilation_unitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProfaneParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] ProfaneParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProfaneParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] ProfaneParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProfaneParser.assign_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign_statement([NotNull] ProfaneParser.Assign_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProfaneParser.assign_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign_statement([NotNull] ProfaneParser.Assign_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProfaneParser.invoke_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInvoke_statement([NotNull] ProfaneParser.Invoke_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProfaneParser.invoke_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInvoke_statement([NotNull] ProfaneParser.Invoke_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProfaneParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] ProfaneParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProfaneParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] ProfaneParser.ExprContext context);
}
